---
output: 
  stevetemplates::cv:
    includes:
      in_header: "preamble.tex"
geometry: margin=0.5in

title: "CV"
author: Waveley Qiu

jobtitle: "MS Biostatistics (Theory and Methods) '23 | Columbia University"
address: "New York, NY"
fontawesome: yes
email: waveley.qiu@columbia.edu
github: waveley

phone: "(408) 888-3438"
web: "linkedin.com/in/waveley"
updated: FALSE
#rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: black
urlcolor: black

---

# Education

## Master's of Sciences, Biostatistics | Theory and Methods Track \hfill 2021 - 2023

Columbia University, Mailman School of Public Health. GPA: 3.958

Relevant Coursework: 

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.025\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::


::: {.col data-latex="{0.475\textwidth}"}
P8104/P9104 - Probability (Master and Doctoral)

P8109/P9109 - Statistical Inference (Master and Doctoral)

P8130/P8131 - Biostatistical Methods 1 and 2     

P8105 - Data Science 1
:::

::: {.col data-latex="{0.025\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::

::: {.col data-latex="{0.475\textwidth}"}

P8160 - Advanced Statistical Computing

P8158 - Latent Variables and Structural Equation Modeling

P8108 - Survival Analysis

P8140 - Randomized Clinical Trials
:::
::::::
   

## Bachelor's of Sciences, Statistics | Linguistics Minor \hfill 2016 - 2020

University of California, Los Angeles


# Skills and Competencies

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.8\textwidth}"}
## Programming Languages

>R -- 5 years of experience. Skilled in `tidyverse` functions, data cleaning, EDA, modeling, and simulations.


>SAS -- 3 years of experience. Skilled in `DATA` step and many `PROC` procedures (`PROC SQL`, `PROC REPORT`, `PROC TABULATE`, `PROC UNIVARIATE`), and the macro language

:::

::: {.col data-latex="{0.025\textwidth}"}
\ 
<!-- an empty Div (with a white space), serving as
a column separator -->
:::

::: {.col data-latex="{0.175\textwidth}"}
## Languages

>English

>Mandarin

:::
::::::

# Projects

## Bayesian Modeling of Hurricane Trajectories \hfill P8160 | Spring 2022 (Team of 6)

>Established a Markov Chain Monte Carlo method (Gibbs Sampler) to estimate parameters of a proposed linear model in a Bayesian framework to estimate hurricane wind speed. 

## Bootstrapping in the Setting of Propensity Score Matching \hfill P8160 | Spring 2022 (Team of 5)

>Designed and executed a Monte-Carlo simulation study evaluating the accuracy of two bootstrap methods in estimating the standard error of average treatment effect when utilizing propensity score modeling in both binary and continuous outcome settings.

## Parking Violations in NYC \hfill P8105 | Fall 2021 (Team of 5)

>Conducted exploratory data analysis using data from OpenNYC to examine the distribution of parking violation tickets across New York City.

>Conducted simple spatial analysis and created interactive maps identifying most commonly ticketed fire hydrants.

# Employment and Experience

## Columbia University in the City of New York

*Graduate Teaching Assistant \hfill January 2022 - present*

>TA for P6110: Statistical Computing with SAS (Spring '22, Fall '22), Summer Institute in Biostatistics and Data Science (Summer '22), and P8105: Data Science 1 (Fall '22).

>Responsiblities include: holding weekly office hours and/or leading recitation, assisting students during lecture, and grading exams and assignments.

\newpage
*Graduate Research Assistant, Department of Environmental Health \hfill March 2022 - present*

>Contributing to the data cleaning and exploration efforts for a multi-country longitudinal study relating occurrences of natural disasters and the onset of the COVID-19 pandemic with childhood health outcomes in Peru, India, Ethiopia, and Vietnam, under the direction of Dr. Ilan Cerna-Turoff. 

>Conducted data quality checks and created tables for manuscript due for submission in December 2022.

*Graduate Research Assistant, Department of Medicine \hfill September 2022 - present*

>Constructed linear mixed models for exploratory analysis in longitudinal study analyzing the bi-directional effects of diet and sleep, under the direction of Dr. Bin Cheng.

>Abstract submitted to EPI|Lifestyle in October 2022.

## YouGov

*SRG Analytics Intern \hfill July 2022 - September 2022*

>Studied the theory underlying YouGov's sample matching methodology and conducted sample matching.

>Developed methodology combining logistic regression and iterative proportional fitting to construct a target frame for sample matching on binary survey outcomes.

## EDETEK, Inc.

*Statistical Programmer I \hfill October 2020 - August 2021*

>Generated production and validation standardized datasets (SDTM/ADaM), tables, lists, and figures (TLFs) for submission to various regulatory agencies and publication groups.

>Worked with data management team to manage data review and generated regular monitoring reports, data reconciliation reports, and programmed edit checks.

>Principally responsible for producing and maintaining protocol deviation listings for several studies.

>Programmed in SAS and SQL (PROC SQL), establishing macros and automating processes in both data review and deliverable production.

*Statistical Programming Intern  \hfill July 2020 - October 2020*

>Assisted in SDTM, ADaM, and TLF generation.

>Assisted data management team in data cleaning process.

>Performed routine data management tasks in reviewing database entries and in opening and closing queries

## Relypsa Inc./Vifor Pharma

*Biometrics Intern \hfill June 2019 - September 2019*

>Generated validation SDTMs after independently learning SAS.

>Assisted in manuscript review.

>Worked with drug safety department and generated a weekly SAE listing.

## UCLA California Nanosystems Institute

*Undergraduate Research Assistant \hfill January 2018 - June 2020*

>Assisted in the manufacturing of nanoparticles.

>Conducted experiments determining drug retention and release.

>Analyzed measurements in Excel and experiment-specific software (CompuSyn).
























